### ISSUE TITLE
首頁橫幅要可以被捲軸一起往上捲，不用凍結在頁面

### ISSUE THREAD

**Issue by phiricen** [phiricen/p076_youth.hakka.gov.tw#189]
- 首頁橫幅要可以被捲軸一起往上捲，不用凍結在頁面
![image](https://user-images.githubusercontent.com/3261097/229265273-a77373b5-bb21-4983-a91d-e5f7bf69f514.png)

**Comment by emi-chang** [comment]
@phiricen 已調整於 [PR 195](https://github.com/phiricen/p076_youth.hakka.gov.tw/pull/195)
