### ISSUE TITLE
多個作答框的模組 e.g. 山形圖、組織思考圖、文氏圖等...

### ISSUE THREAD

**Issue by phiricen** [phiricen/p076_youth.hakka.gov.tw#191]
- 目前要拖曳選項才能作答(沒辦法只用點選，因為這樣選項會直接跑到第一個作答框)
- 點選要作答的作答框，指定現在要回答這一格並讓邊框高亮，再點選選項後，選項就會跑到剛剛指定的那一格作答框

**Comment by emi-chang** [comment]
相關修改提交於 [PR 213](https://github.com/phiricen/p076_youth.hakka.gov.tw/pull/213)
